#!/usr/bin/env bash
# Baseline ratchet for oelint-adv findings.
#
# meta-freescale carries a large body of *accepted* findings: cross-layer
# 'require' false positives, BSP fork/mirror recipes that track upstream
# verbatim, deliberate INSANE_SKIP / override idioms, and so on. Driving the
# layer to zero findings would mean papering it with hundreds of '# nooelint'
# comments, which the layer has deliberately chosen not to do. A plain
# 'oelint-adv exits non-zero on any finding' gate is therefore red on every PR
# and useless here.
#
# Instead this script compares the current findings against a committed baseline
# (oelint-baseline.txt) and fails only on findings that are NOT already in the
# baseline - i.e. regressions introduced by the change under review. The
# accepted residual is allowed to stand; it can only shrink, never grow.
#
# Findings are normalised to 'relpath:oelint.rule.id' (line numbers and messages
# dropped) so that unrelated edits shifting a recipe's line numbers do not read
# as new findings. Counts are significant: a second instance of the same rule in
# the same file is a new finding.
#
# Usage:
#   oelint-ratchet.sh            check current tree against the baseline (CI)
#   oelint-ratchet.sh --update   regenerate the baseline from the current tree
#                                 (run after intentionally fixing/suppressing)
set -euo pipefail

unset CDPATH
here=$(cd -- "$(dirname -- "$0")" && pwd)
layer=$(cd -- "$here/../.." && pwd)
baseline="$here/oelint-baseline.txt"
driver="$here/run-oelint.sh"

# Emit the current findings normalised to 'relpath:oelint.rule.id', sorted.
# Paths are made layer-relative (oelint-adv reports absolute paths here) so the
# baseline is stable across checkouts; line numbers and messages are dropped so
# unrelated line shifts do not read as new findings. run-oelint.sh exits
# non-zero whenever findings exist, so guard the pipeline with '|| true'.
current_findings() {
    "$driver" --quiet --output /dev/stdout 2>/dev/null \
        | awk -F: -v pfx="$layer/" '
            NF>=4 && $4 ~ /^oelint\./ {
                p = $1
                if (index(p, pfx) == 1) p = substr(p, length(pfx) + 1)
                sub(/^\.\//, "", p)
                print p ":" $4
            }' \
        | sort || true
}

if [ "${1:-}" = "--update" ]; then
    {
        echo "# oelint-adv finding baseline for meta-freescale - DO NOT EDIT BY HAND."
        echo "# Generated by contrib/oelint/oelint-ratchet.sh --update. Each line is a"
        echo "# 'relpath:oelint.rule.id' accepted finding; the CI ratchet fails only on"
        echo "# findings not listed here. Regenerate after intentionally fixing or"
        echo "# suppressing findings; the count should only ever go down."
        current_findings
    } > "$baseline"
    echo "Wrote $(grep -cvE '^\s*(#|$)' "$baseline") findings to ${baseline#"$here"/}"
    exit 0
fi

if [ ! -f "$baseline" ]; then
    echo "error: baseline not found at $baseline" >&2
    echo "generate it with: $0 --update" >&2
    exit 2
fi

mapfile -t current < <(current_findings)

# Baseline multiset counts (skip comments / blank lines).
declare -A base
while IFS= read -r line; do
    case "$line" in ''|\#*) continue ;; esac
    base["$line"]=$(( ${base["$line"]:-0} + 1 ))
done < "$baseline"

# Walk current findings; anything exceeding its baseline count is new.
declare -A seen
new=()
for k in "${current[@]:-}"; do
    [ -n "$k" ] || continue
    seen["$k"]=$(( ${seen["$k"]:-0} + 1 ))
    if [ "${seen[$k]}" -gt "${base[$k]:-0}" ]; then
        new+=("$k")
    fi
done

baseline_count=$(grep -cvE '^\s*(#|$)' "$baseline")
if [ "${#new[@]}" -gt 0 ]; then
    echo "oelint ratchet: ${#new[@]} new finding(s) not in the baseline:" >&2
    printf '  %s\n' "${new[@]}" >&2
    echo >&2
    echo "Fix each finding, or - if it is a genuine false positive - add an inline" >&2
    echo "'# nooelint: <rule.id>' next to it and regenerate the baseline with:" >&2
    echo "  contrib/oelint/oelint-ratchet.sh --update" >&2
    exit 1
fi

echo "oelint ratchet: no new findings (${#current[@]} current / ${baseline_count} baseline)."
